on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Debug secrets
        run: |
          echo "DATABASE_URL exists: ${{ secrets.DATABASE_URL != '' }}"
          echo "JWT_SECRET exists: ${{ secrets.JWT_SECRET != '' }}"
          echo "JWT_EXPIRATION exists: ${{ secrets.JWT_EXPIRATION != '' }}"
          echo "SSH_PASSWORD exists: ${{ secrets.SSH_PASSWORD != '' }}"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: "103.187.146.181"
          username: "erwindevmail"
          password: ${{ secrets.SSH_PASSWORD }}
          envs: DATABASE_URL,JWT_SECRET,JWT_EXPIRATION
          debug: true
          script: |
            echo "Current directory: $(pwd)"
            cd /home/erwindevmail/mini-app/backend
            echo "After cd: $(pwd)"
            git pull origin master
            npm install
            npm run build
            pm2 restart backend
