on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master

    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
      SSH_PASSWORD: ${{ vars.SSH_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Environment check:"
          echo "SSH_PASSWORD exists: ${{ vars.SSH_PASSWORD != '' }}"
          echo "DATABASE_URL exists: ${{ vars.DATABASE_URL != '' }}"

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: "103.187.146.181"
          username: "erwindevmail"
          password: ${{ vars.SSH_PASSWORD }}
          script: |
            cd /home/erwindevmail/mini-app-secure-code/backend
            git pull origin master
            npm install
            npm run build
            pm2 restart backend
