on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    env:
      DATABASE_URL: postgresql://nestuser:nestpassword@103.187.146.181:5433/secure_app
      JWT_SECRET: secure_jwt_secret
      JWT_EXPIRATION: 3600s

    steps:
      - uses: actions/checkout@v4

      - name: Debug Environment
        run: |
          echo "Environment check:"
          echo $DATABASE_URL
          echo $JWT_SECRET
          echo $JWT_EXPIRATION

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: "103.187.146.181"
          username: "erwindevmail"
          password: ${{ secrets.SSH_PASSWORD }}
          envs: DATABASE_URL,JWT_SECRET,JWT_EXPIRATION
          script: |
            cd /home/erwindevmail/mini-app/backend
            git pull origin master
            npm install
            npm run build
            pm2 restart backend
