on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: master
    env:
      DATABASE_URL: ${{ vars.DATABASE_URL }}
      JWT_SECRET: ${{ vars.JWT_SECRET }}
      JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
      SSH_PASSWORD: ${{ vars.SSH_PASSWORD }}
    steps:
      - uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: "103.187.146.181"
          username: "erwindevmail"
          password: ${{ vars.SSH_PASSWORD }}
          script: |
            cd /home/erwindevmail/mini-app-secure-code
            git pull
            cd /home/erwindevmail/mini-app-secure-code/backend
            docker compose down
            docker compose build --no-cache
            docker compose up -d
